fun main() = try {

}
catch(e: NumberFormatException) { println("Введено недопустимое значение") }